language: node_js
node_js:
  - "12.18.3"
before_install:
  - npm install -g yarn
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - yongwon0824@naver.com
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
before_deploy:
  - mkdir -p before-deploy
  - cp deploy.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build before-deploy/
  - cd before-deploy && zip -r before-deploy * # Before-deploy folder 압축
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/yirang-front.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yirang-react
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yirang-react
    key: yirang-front.zip
    bundle_type: zip
    application: yirang-spring-api
    deployment_group: yirang-spring 
    region: ap-northeast-2
    wait_until_deployed: true